
----------------------header--------------------------
2017-02-15 13:35:06,183 [4] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 一个封锁操作被对 WSACancelBlockingCall 的调用中断。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 73

2017-02-15 13:35:09,490 [7] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 73


----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 13:40:00,749 [3] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 192.168.1.76:8888
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 集中器控制客户端.HandleClass.HandleTool.ToThreadCreateSocket(Object obj) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 136

2017-02-15 13:41:01,890 [5] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.Net.UnsafeNclNativeMethods.OSSOCK.recv(IntPtr socketHandle, Byte* pinnedBuffer, Int32 len, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 72

2017-02-15 13:48:07,956 [3] ERROR errorMsg - System.Data.SQLite.SQLiteException (0x80004005): The database file is locked
database is locked
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 集中器控制客户端.HandleClass.SQLiteHelper.ExecuteNonQuery(String sql, SQLiteParameter[] parameters) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\SQLiteHelper.cs:行号 67

2017-02-15 13:48:13,878 [10] ERROR errorMsg - System.Data.SQLite.SQLiteException (0x80004005): The database file is locked
database is locked
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 集中器控制客户端.HandleClass.SQLiteHelper.ExecuteNonQuery(String sql, SQLiteParameter[] parameters) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\SQLiteHelper.cs:行号 67

2017-02-15 13:48:15,394 [11] ERROR errorMsg - System.Data.SQLite.SQLiteException (0x80004005): The database file is locked
database is locked
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 集中器控制客户端.HandleClass.SQLiteHelper.ExecuteNonQuery(String sql, SQLiteParameter[] parameters) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\SQLiteHelper.cs:行号 67

2017-02-15 13:48:18,988 [8] ERROR errorMsg - System.Data.SQLite.SQLiteException (0x80004005): The database file is locked
database is locked
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 集中器控制客户端.HandleClass.SQLiteHelper.ExecuteNonQuery(String sql, SQLiteParameter[] parameters) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\SQLiteHelper.cs:行号 67

2017-02-15 13:48:26,254 [7] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 72

2017-02-15 13:48:38,442 [3] ERROR errorMsg - System.Data.SQLite.SQLiteException (0x80004005): The database file is locked
database is locked
   在 System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   在 System.Data.SQLite.SQLiteDataReader.NextResult()
   在 System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   在 System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   在 System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   在 集中器控制客户端.HandleClass.SQLiteHelper.ExecuteNonQuery(String sql, SQLiteParameter[] parameters) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\SQLiteHelper.cs:行号 67

2017-02-15 13:50:13,103 [5] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 由于套接字没有连接并且(当使用一个 sendto 调用发送数据报套接字时)没有提供地址，发送或接收数据的请求没有被接受。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 72

2017-02-15 13:50:15,416 [14] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 72

2017-02-15 13:51:20,973 [5] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 72


----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 14:00:00,895 [4] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 73


----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 14:03:25,713 [13] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 73

2017-02-15 14:03:27,650 [17] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 73

2017-02-15 14:03:36,631 [12] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 73

2017-02-15 14:03:42,696 [11] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.Threading.Thread.AbortInternal()
   在 System.Threading.Thread.Abort()
   在 集中器控制客户端.HandleClass.HandleTool.stopSocket() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 277
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 76


----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 14:11:39,337 [12] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.Threading.Thread.AbortInternal()
   在 System.Threading.Thread.Abort()
   在 集中器控制客户端.HandleClass.HandleTool.CloseThread() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 326
   在 集中器控制客户端.HandleClass.HandleTool.stopSocket() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 270
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 77

2017-02-15 14:11:58,149 [10] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.Net.Sockets.Socket.UpdateStatusAfterSocketError(SocketError errorCode)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:12:01,601 [11] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:12:14,432 [9] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.Threading.Thread.AbortInternal()
   在 System.Threading.Thread.Abort()
   在 集中器控制客户端.HandleClass.HandleTool.CloseThread() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 326
   在 集中器控制客户端.HandleClass.HandleTool.stopSocket() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 270
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 77

2017-02-15 14:12:18,385 [12] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.Net.UnsafeNclNativeMethods.OSSOCK.recv(IntPtr socketHandle, Byte* pinnedBuffer, Int32 len, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:12:25,637 [16] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:12:32,182 [11] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:12:37,292 [15] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:12:51,513 [11] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 一个封锁操作被对 WSACancelBlockingCall 的调用中断。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:13:46,965 [10] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:13:51,057 [11] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:13:57,729 [10] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:14:01,982 [11] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:14:17,666 [10] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:14:21,167 [11] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:14:26,103 [10] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.Net.UnsafeNclNativeMethods.OSSOCK.recv(IntPtr socketHandle, Byte* pinnedBuffer, Int32 len, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:14:33,572 [11] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:15:16,056 [16] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 14:16:29,182 [12] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 192.168.1.76:8888
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 集中器控制客户端.HandleClass.HandleTool.ToThreadCreateSocket(Object obj) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 138

2017-02-15 14:16:32,683 [11] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 192.168.1.76:8888
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 集中器控制客户端.HandleClass.HandleTool.ToThreadCreateSocket(Object obj) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 138


----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 14:38:06,419 [11] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 192.168.1.76:8888
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 集中器控制客户端.HandleClass.HandleTool.ToThreadCreateSocket(Object obj) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 138

2017-02-15 14:38:09,323 [12] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 192.168.1.76:8888
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 集中器控制客户端.HandleClass.HandleTool.ToThreadCreateSocket(Object obj) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 138


----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 14:39:22,843 [3] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 192.168.1.76:8888
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 集中器控制客户端.HandleClass.HandleTool.ToThreadCreateSocket(Object obj) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 138

2017-02-15 14:39:25,266 [4] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 192.168.1.76:8888
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 集中器控制客户端.HandleClass.HandleTool.ToThreadCreateSocket(Object obj) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 138

2017-02-15 14:39:31,698 [5] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 192.168.1.76:8888
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 集中器控制客户端.HandleClass.HandleTool.ToThreadCreateSocket(Object obj) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 138


----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 14:50:06,984 [1] ERROR errorMsg - System.UnauthorizedAccessException: 对端口“COM1”的访问被拒绝。
   在 System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   在 System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   在 System.IO.Ports.SerialPort.Open()
   在 集中器控制客户端.PortSetting.btn_OpenPort_Click(Object sender, EventArgs e) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\PortSetting.cs:行号 77


----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 14:54:34,980 [1] ERROR errorMsg - System.UnauthorizedAccessException: 对端口“COM1”的访问被拒绝。
   在 System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   在 System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   在 System.IO.Ports.SerialPort.Open()
   在 集中器控制客户端.PortSetting.btn_OpenPort_Click(Object sender, EventArgs e) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\PortSetting.cs:行号 77


----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 14:58:47,380 [1] ERROR errorMsg - System.UnauthorizedAccessException: 对端口“COM1”的访问被拒绝。
   在 System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   在 System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   在 System.IO.Ports.SerialPort.Open()
   在 集中器控制客户端.PortSetting.btn_OpenPort_Click(Object sender, EventArgs e) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\PortSetting.cs:行号 77


----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 15:05:34,577 [1] ERROR errorMsg - System.UnauthorizedAccessException: 对端口“COM1”的访问被拒绝。
   在 System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   在 System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   在 System.IO.Ports.SerialPort.Open()
   在 集中器控制客户端.PortSetting.btn_OpenPort_Click(Object sender, EventArgs e) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\PortSetting.cs:行号 77

2017-02-15 15:05:36,590 [1] ERROR errorMsg - System.UnauthorizedAccessException: 对端口“COM1”的访问被拒绝。
   在 System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   在 System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   在 System.IO.Ports.SerialPort.Open()
   在 集中器控制客户端.PortSetting.btn_OpenPort_Click(Object sender, EventArgs e) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\PortSetting.cs:行号 77


----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 15:09:24,984 [1] ERROR errorMsg - System.UnauthorizedAccessException: 对端口“COM1”的访问被拒绝。
   在 System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   在 System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   在 System.IO.Ports.SerialPort.Open()
   在 集中器控制客户端.PortSetting.btn_OpenPort_Click(Object sender, EventArgs e) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\PortSetting.cs:行号 77


----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 15:14:13,096 [1] ERROR errorMsg - System.UnauthorizedAccessException: 对端口“COM1”的访问被拒绝。
   在 System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   在 System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   在 System.IO.Ports.SerialPort.Open()
   在 集中器控制客户端.PortSetting.btn_OpenPort_Click(Object sender, EventArgs e) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\PortSetting.cs:行号 77

2017-02-15 15:14:38,643 [4] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 一个封锁操作被对 WSACancelBlockingCall 的调用中断。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 15:14:40,568 [9] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 15:14:42,434 [4] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 15:14:44,564 [8] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 15:14:46,978 [4] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 15:14:49,267 [9] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 15:14:51,298 [4] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 15:14:53,282 [8] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 15:14:55,115 [4] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 15:14:57,130 [8] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 15:14:59,242 [4] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 15:15:01,554 [6] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 15:15:08,818 [4] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74


----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 16:27:54,371 [3] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 192.168.1.76:8888
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 集中器控制客户端.HandleClass.HandleTool.ToThreadCreateSocket(Object obj) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 138


----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 17:08:14,752 [12] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 一个封锁操作被对 WSACancelBlockingCall 的调用中断。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 17:08:18,253 [15] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 17:08:23,185 [12] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 17:08:26,214 [14] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 一个封锁操作被对 WSACancelBlockingCall 的调用中断。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74


----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 17:08:41,549 [12] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 一个封锁操作被对 WSACancelBlockingCall 的调用中断。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 17:08:52,900 [15] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 17:09:19,018 [13] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 集中器控制客户端.HandleClass.reportModels.ClientReport.get_REPORT_BODY()
   在 集中器控制客户端.HandleClass.BytesSerialize.clientReportUnSerialize(ClientReport data) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\BytesSerialize.cs:行号 33

2017-02-15 17:09:19,072 [6] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 192.168.1.76:8888
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 集中器控制客户端.HandleClass.HandleTool.ToThreadCreateSocket(Object obj) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 138

2017-02-15 17:09:19,118 [13] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 集中器控制客户端.HandleClass.BytesSerialize.clientReportUnSerialize(ClientReport data) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\BytesSerialize.cs:行号 130
   在 集中器控制客户端.HandleClass.HandleTool.theSocketSend[T](Byte bty, T t) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 303
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 92

2017-02-15 17:09:30,781 [14] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.Threading.Thread.AbortInternal()
   在 System.Threading.Thread.Abort()
   在 集中器控制客户端.HandleClass.HandleTool.CloseThread() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 325
   在 集中器控制客户端.HandleClass.HandleTool.stopSocket() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 270
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 77

2017-02-15 17:09:35,113 [12] ERROR errorMsg - System.ObjectDisposedException: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
   在 System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   在 System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Send(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.sendInfo(Byte[] info) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 287

2017-02-15 17:09:43,419 [9] ERROR errorMsg - System.ObjectDisposedException: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
   在 System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   在 System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Send(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.sendInfo(Byte[] info) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 287

2017-02-15 17:10:14,494 [11] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 一个封锁操作被对 WSACancelBlockingCall 的调用中断。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 17:10:14,494 [15] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 一个封锁操作被对 WSACancelBlockingCall 的调用中断。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 17:10:15,781 [13] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 192.168.1.76:8888
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 集中器控制客户端.HandleClass.HandleTool.ToThreadCreateSocket(Object obj) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 138

2017-02-15 17:10:15,830 [17] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   在 System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 86

2017-02-15 17:10:18,649 [10] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 192.168.1.76:8888
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 集中器控制客户端.HandleClass.HandleTool.ToThreadCreateSocket(Object obj) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 138

2017-02-15 17:10:23,812 [20] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.Net.UnsafeNclNativeMethods.OSSOCK.recv(IntPtr socketHandle, Byte* pinnedBuffer, Int32 len, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74


----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 17:13:31,633 [3] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 116.226.184.235:8888
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 集中器控制客户端.HandleClass.HandleTool.ToThreadCreateSocket(Object obj) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 138


----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 17:16:31,067 [4] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 一个封锁操作被对 WSACancelBlockingCall 的调用中断。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74


----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 17:18:22,751 [4] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74


----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------

----------------------footer--------------------------

----------------------header--------------------------
2017-02-15 17:53:18,567 [3] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 你的主机中的软件中止了一个已建立的连接。 192.168.1.72:8887
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 集中器控制客户端.HandleClass.HandleTool.ToThreadCreateSocket(Object obj) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 139

2017-02-15 17:53:34,053 [8] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.Threading.Thread.AbortInternal()
   在 System.Threading.Thread.Abort()
   在 集中器控制客户端.HandleClass.HandleTool.CloseThread() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 326
   在 集中器控制客户端.HandleClass.HandleTool.stopSocket() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 271
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 77

2017-02-15 17:53:37,577 [1] ERROR errorMsg - System.ObjectDisposedException: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。
   在 System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   在 System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Send(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.sendInfo(Byte[] info) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 288

2017-02-15 18:01:44,345 [3] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 18:01:47,908 [7] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 18:01:55,955 [4] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 18:01:58,764 [7] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 18:02:01,579 [3] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 18:02:01,695 [9] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   在 System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   在 System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   在 集中器控制客户端.HandleClass.BytesSerialize.clientReportSerialize(Byte[] data) 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\BytesSerialize.cs:行号 149

2017-02-15 18:02:14,061 [7] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 System.Threading.Thread.AbortInternal()
   在 System.Threading.Thread.Abort()
   在 集中器控制客户端.HandleClass.HandleTool.CloseThread() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 326
   在 集中器控制客户端.HandleClass.HandleTool.stopSocket() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 271
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 77

2017-02-15 18:03:48,899 [3] ERROR errorMsg - System.Threading.ThreadAbortException: 正在中止线程。
   在 Microsoft.Win32.SafeNativeMethods.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   在 System.ComponentModel.Win32Exception.TryGetErrorMessage(Int32 error, StringBuilder sb, String& errorMsg)
   在 System.ComponentModel.Win32Exception.GetErrorMessage(Int32 error)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74

2017-02-15 18:05:00,496 [8] ERROR errorMsg - System.Net.Sockets.SocketException (0x80004005): 你的主机中的软件中止了一个已建立的连接。
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   在 System.Net.Sockets.Socket.Receive(Byte[] buffer)
   在 集中器控制客户端.HandleClass.HandleTool.ReceiveInfo() 位置 e:\work\WindowsFormsApplication4\WindowsFormsApplication4\WindowsFormsApplication4\HandleClass\HandleTool.cs:行号 74


----------------------footer--------------------------
